Compute the z500 anomalies: false
DIR_IN: /media/data/mjo/MJO-Teleconnections-develop/data
Daily Anomaly: false
END_DATE: '20180315'
ERAI: true
IMERG: true
Number of ensembles: 1
Path to OLR model data files: /media/data/mjo/MJO-Teleconnections-develop/data/
Path to OLR observation data files: /media/data/mjo/MJO-Teleconnections-develop/data/OBS/
Path to T2m model data files for date: /media/data/mjo/MJO-Teleconnections-develop/data/
Path to T2m observation data files: /media/data/mjo/MJO-Teleconnections-develop/data/OBS/
Path to Z500 model data files: /media/data/mjo/MJO-Teleconnections-develop/data/
Path to Z500 observation data files: /media/data/mjo/MJO-Teleconnections-develop/data/OBS/
Path to meridional wind at 500 hPa model data files: /media/data/mjo/MJO-Teleconnections-develop/data/
Path to meridional wind at 500 hPa observation data files: /media/data/mjo/MJO-Teleconnections-develop/data/OBS/
Path to meridional wind at 850 hPa model data files: /media/data/mjo/MJO-Teleconnections-develop/data/
Path to meridional wind at 850 hPa observation data files: /media/data/mjo/MJO-Teleconnections-develop/data/OBS/
Path to precipitation model data files: /media/data/mjo/MJO-Teleconnections-develop/data/
Path to precipitation observation data files: /media/data/mjo/MJO-Teleconnections-develop/data/OBS/
Path to temperature at 500 hPa model data files: /media/data/mjo/MJO-Teleconnections-develop/data/
Path to temperature at 500 hPa observation data files: /media/data/mjo/MJO-Teleconnections-develop/data/OBS/
Path to z100 date files: /media/data/mjo/MJO-Teleconnections-develop/data/
Path to z100 observation files: /media/data/mjo/MJO-Teleconnections-develop/data/OBS/
Path to zonal wind at 10 hPa model data files: /media/data/mjo/MJO-Teleconnections-develop/data/
Path to zonal wind at 10 hPa observation data files: /media/data/mjo/MJO-Teleconnections-develop/data/OBS/
Path to zonal wind at 200 hPa model data files: /media/data/mjo/MJO-Teleconnections-develop/data/
Path to zonal wind at 200 hPa observation data files: /media/data/mjo/MJO-Teleconnections-develop/data/OBS/
Path to zonal wind at 850 hPa model data files: /media/data/mjo/MJO-Teleconnections-develop/data/
Path to zonal wind at 850 hPa observation data files: /media/data/mjo/MJO-Teleconnections-develop/data/OBS/
RMM: false
START_DATE: '20111101'
Initial dates: 
- 1
- 15
forecast time step: 24
length of forecasts: '46'
model data daily-mean values: true
model initial conditions: true
model name: UFS5
selected:
- 6
smooth climatology: false
