'Compute the z500 anomalies:': false
DIR_IN: '1'
'Daily Anomaly:': true
'END_DATE:': '1'
'ERAI:': true
'IMERG:': true
'Initial dates:':
- 1
'Model input file daily mean:': false
'Number of ensembles:': '1'
'Number of initial dates:': 1
'Path to OLR data files:': 1/OBS/
Path to T2m model data files for date:
- 1/
'Path to T2m observational data files:': 1/OBS/
Path to meridional wind at 500 hPa date files:
- 1/
'Path to meridional wind at 500 hPa observational data files:': 1/OBS/
Path to meridional wind at 850 hPa date files:
- 1/
Path to meridional wind at 850 hPa observational data file: 1/OBS/
'Path to precipitation data files:':
- 1/
'Path to precipitation observational data files:': 1/OBS/
Path to temperature at 500 hPa data files:
- 1/
Path to temperature at 500 hPa observational data files: 1/OBS/
Path to z100 date files:
- 1/
Path to z100 observational files: 1/OBS/
Path to z500 date files:
- 1/
Path to z500 observational files: 1/OBS/
'Path to zonal wind at 10 hPa data files:':
- 1/
'Path to zonal wind at 10 hPa observational data files:': 1/OBS/
'Path to zonal wind at 200 hPa data files:':
- 1/
'Path to zonal wind at 200 hPa observational data files:': 1/OBS/
'Path to zonal wind at 850 hPa data files:': 1/OBS/
Path to zonalwind850 date files:
- 1/
Path to zonalwind850 observational files: 1/OBS/
'RMM:': false
'START_DATE:': '1'
'Select weeks:': ''
forecast time step: 24
'length of forecasts:': '1'
model initial conditions: false
model name: UFS5
selected:
- 1
- 10
'smooth climatology:': false
