Compute the z500 anomalies: false
DIR_IN: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data
Daily Anomaly: true
END_DATE: '20180419'
ERAI: true
IMERG: true
Initial dates:
- 1
- 15
Number of ensembles: '1'
Number of initial dates: 2
Path to OLR model data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/
Path to OLR observation data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/OBS/
Path to T2m model data files for date: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/
Path to T2m observation data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/OBS/
Path to Z500 model data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/Prototype5/gh/
Path to Z500 observation data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/OBS/
Path to meridional wind at 500 hPa model data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/
Path to meridional wind at 500 hPa observation data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/OBS/
Path to meridional wind at 850 hPa model data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/
Path to meridional wind at 850 hPa observation data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/OBS/
Path to precipitation model data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/Prototype5/prate/
Path to precipitation observation data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/OBS/
Path to temperature at 500 hPa model data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/
Path to temperature at 500 hPa observation data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/OBS/
Path to z100 date files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/
Path to z100 observation files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/OBS/
Path to zonal wind at 10 hPa model data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/
Path to zonal wind at 10 hPa observation data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/OBS/
Path to zonal wind at 200 hPa model data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/
Path to zonal wind at 200 hPa observation data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/OBS/
Path to zonal wind at 850 hPa model data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/
Path to zonal wind at 850 hPa observation data files: /home/server/hpc/jenneylab/bridges2_transfer/ufs_data/OBS/
RMM: false
START_DATE: '20110401'
forecast time step: 24
length of forecasts: '35'
model data daily-mean values: true
model initial conditions: true
model name: UFS5
selected:
- 1
- 2
smooth climatology: false
