- DIR_IN: /projects/cstan
- 'START_DATE:': '2011-01-01'
- 'END_DATE:': '2018-12-31'
- 'Number of ensembles:': '1'
- 'Number of initial dates:': '2'
- 'ERAI:': true
- 'IMERG:': true
- 'Daily Anomaly:': true
- 'RMM:': false 
- z500: ''
- z500 observational files: ''
- z100: ''
- z100 observational files: ''
- zonalwind850: ''
- zonalwind850 observational files: ''
- meridional wind at 850 hPa data file: ''
- meridional wind at 850 hPa observational data file: ''
- 'Path to meridional wind at 500 hPa data files:': ''
- 'Path to meridional wind at 500 hPa data files:': ''
- 'zonal wind at 10 hPa data files:': ''
- 'zonal wind at 10 hPa data files:': ''
- temperature at 500 hPa data files: ''
- temperature at 500 hPa data files: ''
- 'Path to precipitation data files:': ''
- 'Path to precipitation data files:': ''
